[package]
name = "rock_paper_scisors_cellular_automata"
version = "0.1.0"
authors = ["dmoria"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.2.9"